version: '3'
services:
  php:
    build: ./docker
    volumes:
      - ./symfony/:/app
    working_dir: /app
    networks:
      - main
  web:
    image: nginx
    volumes:
      - ./symfony/public:/app/public
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - main
  postgres:
    image: postgres:11.2
    restart: always
    environment:
      POSTGRES_PASSWORD: test1
      #POSTGRES_DB: currency
    ports:
      - 5432:5432
    networks:
      - main

networks:
  main:
