framework:
    workflows:
        blog:
            type: 'workflow'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentPlace'
            supports:
                - App\Entity\Currency
            initial_marking: started
            places:
                - started
                - rewiew
                - writed
                - updated
            transitions:
                start:
                    from: started
                    to:   rewiew
                write:
                    from: rewiew
                    to:   writed
                update:
                    from: rewiew
                    to:   updated